aseurl = "https://www.example.com/"
title = "Vignesh Krishnamoorthy"
author = "Vignesh Krishnamoorthy"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Vignesh Krishnamoorthy"
  piwiktracking = "//analytics.vigneshkrishnamoorthy.me/piwik/"
  fathomtracking = "//fathom.vigneshkrishnamoorthy.me/tracker.js"

[[menu.main]]
    name = "Home"
    url = "/"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/vignkri"
[[menu.main]]
    name = "Resume"
    url  = "https://linkedin.com/in/vigneshkrishnamoorthy/"
[[menu.main]]
    name = "Notes"
    url = "/notes"
